
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: 35462213
  pool: 5

development:
  <<: *default
  database: foods_development


test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: foods_production
  username: foods
  password: <%= ENV['FOODS_DATABASE_PASSWORD'] %>
